name: Railway Stop (23:00 Asia/Barnaul)

on:
  schedule:
    - cron: "0 16 * * *"  # 16:00 UTC = 23:00 в Asia/Barnaul (UTC+7)
  workflow_dispatch: {}

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Жёстко: удалить последний деплой (как «стоп»)
      - name: Remove latest deployment
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Project Token от нужного Environment
        run: npx -y @railway/cli@latest down -y

      # Мягкая альтернатива (если хочешь останавливать через флаг окружения):
      # - name: Disable app via env flag
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      #   run: |
      #     npx -y @railway/cli@latest variables --set APP_ENABLED=false
      #     npx -y @railway/cli@latest redeploy -y
