name: Railway Start (11:00 Asia/Barnaul)

on:
  schedule:
    - cron: "0 4 * * *"   # 04:00 UTC = 11:00 Барнаул (UTC+7)
  workflow_dispatch: {}

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Redeploy latest (restart service)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: npx -y @railway/cli@latest redeploy -y
