name: Railway Stop via Env Flag (23:00 Asia/Barnaul)

on:
  schedule:
    - cron: "0 16 * * *"   # 16:00 UTC = 23:00 Барнаул (UTC+7)
  workflow_dispatch: {}

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link by IDs
        run: |
          npx -y @railway/cli@latest link \
            --project "${{ secrets.RAILWAY_PROJECT_ID }}" \
            --service "${{ secrets.RAILWAY_SERVICE_ID }}" \
            --environment "production"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Disable app via env var
        run: |
          npx -y @railway/cli@latest variables \
            --service "${{ secrets.RAILWAY_SERVICE_ID }}" \
            --environment "production" \
            --set "APP_ENABLED=false"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Redeploy to apply flag
        run: npx -y @railway/cli@latest redeploy --service "${{ secrets.RAILWAY_SERVICE_ID }}" -y
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
