name: Railway Stop (23:00 Asia/Barnaul)

on:
  schedule:
   - cron: "0 20 * * *"   # 20:00 UTC = 03:00 Asia/Barnaul
  workflow_dispatch: {}

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove latest deployment (stop)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          npx -y @railway/cli@latest down \
            --service "${{ secrets.RAILWAY_SERVICE_ID }}" \
            -y
