name: Railway Stop (03:00 Asia/Barnaul)

on:
  schedule:
    - cron: "0 20 * * *"  # 20:00 UTC = 03:00 Барнаул
  workflow_dispatch: {}

jobs:
  stop:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Link and stop
        run: |
          npx -y @railway/cli link --project "${{ secrets.RAILWAY_PROJECT }}" --service "${{ secrets.RAILWAY_SERVICE }}" --environment production
          npx -y @railway/cli service stop --service "${{ secrets.RAILWAY_SERVICE }}" || npx -y @railway/cli down || true
