name: Railway Stop (03:00 Asia/Barnaul)

on:
  schedule:
    - cron: "0 20 * * *"  # 20:00 UTC = 03:00 Барнаул (UTC+7)
  workflow_dispatch: {}

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets presence
        run: |
          echo "RAILWAY_TOKEN set?    -> ${{ secrets.RAILWAY_TOKEN != '' }}"
          echo "RAILWAY_PROJECT_ID?   -> ${{ secrets.RAILWAY_PROJECT_ID != '' }}"
          echo "RAILWAY_SERVICE_ID?   -> ${{ secrets.RAILWAY_SERVICE_ID != '' }}"

      - name: Auth check (whoami)
        run: npx -y @railway/cli whoami
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Link by IDs and stop
        run: |
          npx -y @railway/cli link --project "${{ secrets.RAILWAY_PROJECT_ID }}" --service "${{ secrets.RAILWAY_SERVICE_ID }}" --environment production
          npx -y @railway/cli service stop --service "${{ secrets.RAILWAY_SERVICE_ID }}" || npx -y @railway/cli down || true
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
