name: Railway Start (11:00 Asia/Barnaul)

on:
  schedule:
    - cron: "0 4 * * *"   # 04:00 UTC = 11:00 в Asia/Barnaul (UTC+7)
  workflow_dispatch: {}

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Быстрый перезапуск последнего деплоя в выбранном Environment
      - name: Redeploy latest
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Project Token от нужного Environment
        run: npx -y @railway/cli@latest redeploy -y

      # Если нужно задеплоить текущий код из репо вместо рестарта, поменяй шаг выше на этот:
      # - name: Deploy repo (up)
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      #   run: npx -y @railway/cli@latest up --ci --detach
