name: Railway Start (11:00 Asia/Barnaul)
on:
  schedule:
    - cron: "0 4 * * *"   # 04:00 UTC = 11:00 Барнаул
  workflow_dispatch: {}

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Login to Railway
        run: railway login --token "${{ secrets.RAILWAY_TOKEN }}"
      - name: Link by names (project/service)
        run: railway link --project "${{ secrets.RAILWAY_PROJECT }}" --service "${{ secrets.RAILWAY_SERVICE }}"
      - name: Start (deploy latest)
        run: railway up --detach || true
