name: Railway Token Check
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Debug secrets (only lengths)
        run: |
          echo "RAILWAY_TOKEN length: ${#RAILWAY_TOKEN}"
          echo "PROJECT_ID set?      : ${{ secrets.RAILWAY_PROJECT_ID != '' }}"
          echo "SERVICE_ID set?      : ${{ secrets.RAILWAY_SERVICE_ID != '' }}"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Whoami (must succeed)
        run: npx -y @railway/cli whoami
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
