# .github/workflows/railway-start.yml
name: Railway Start (11:00 Asia/Barnaul)

on:
  schedule:
    - cron:  "0 4 * * *"   # 04:00 UTC = 11:00 Барнаул (UTC+7)
  workflow_dispatch: {}

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Экспорт токена Railway
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

      - name: Проверка авторизации
        run: npx -y @railway/cli whoami

      - name: Привязка и запуск сервиса
        run: |
          npx -y @railway/cli link \
            --project "${{ secrets.RAILWAY_PROJECT }}" \
            --service "${{ secrets.RAILWAY_SERVICE }}" \
            --environment "${{ secrets.RAILWAY_ENVIRONMENT || 'production' }}"
          npx -y @railway/cli up --detach